### ISSUE TITLE
Server crash, possibly related to Parry

### ISSUE THREAD

**Issue by NielsPilgaard** [Drullkus/Shield-Parry#11]
Details: https://github.com/EnigmaticaModpacks/Enigmatica8/issues/222

I hope relaying like this is alright, I'm kinda pressed for time atm :P

**Comment by TelepathicGrunt** [comment]
For documentation purpose, this line is the problem and causes a deadlock: https://github.com/Drullkus/Shield-Parry/blob/525f4773927cc1d56fdb625e2316a148f67c25b5/src/main/java/us/drullk/parry/ShieldParry.java#L92

This is due to this forge bug where canceling the projectile impact event for piercing arrows will cause an infinite loop and deadlock the game: https://github.com/MinecraftForge/MinecraftForge/issues/9370

**Comment by Shadows-of-Fire** [comment]
https://github.com/MinecraftForge/MinecraftForge/issues/9370

**Comment by Drullkus** [comment]
Fixed via 365264f
